@host = http://localhost
@port = 3000
@apiUsers = /api/users
@apiGames = /api/games

GET {{host}}:{{port}}{{apiGames}}/1
###
GET {{host}}:{{port}}{{apiGames}}/paginate/0
###
GET {{host}}:{{port}}{{apiGames}}/paginate/0/name/destiny
###
GET {{host}}:{{port}}{{apiGames}}/paginate/0/category/indie
###
POST {{host}}:{{port}}{{apiUsers}}
Content-Type: application/json

{
    "username": "holi",
    "password": "holamigos",
    "email": "yepa@gmail.com",
    "fecha_nacimiento": "1980-12-05"
}
###

PUT {{host}}:{{port}}{{apiUsers}}/1
Content-Type: application/json

{
    "username": "rafael",
    "password": "holamigos",
    "email": "otro@gmail.com",
    "active": 0,
    "fecha_nacimiento": "1980-06-05",
    "foto_perfil_url": "",
    "validado": 0
}


